version: "3"
services:
  app:
    image: igor875126/checkmk:1.6.0p16
    container_name: checkmk
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./sites:/omd/sites
    environment:
      TIMEZONE: "Asia/Almaty"
      HOSTNAME: "checkmk.example.com"
      MAIL_RELAY_HOST: "smtp.gmail.com"
      MAIL_RELAY_PORT: "587"
      MAIL_RELAY_USERNAME: "yourname@gmail.com"
      MAIL_RELAY_PASSWORD: ""
